# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-copy-sync:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run:
          name: Install NPM
          command: npm install
      - run:
          name: Webpack
          command: npm run webpack
      - aws-s3/copy:
          from: public/index.html
          to: 's3://techgem1986'
      - aws-s3/sync:
          from: public/static
          to: 's3://techgem1986/static'
workflows:
  build-and-upload-to-S3:
    jobs:
      - build-copy-sync:
          context:
            - AWS