# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-s3: circleci/aws-s3@3.0.0

jobs:
  build-and-upload:
    docker:
      - image: cimg/python:3.6
    steps:
      - checkout
      - node/install:
          node-version: '16.13'
      - run:
          name: Installing Ract JS Libraries
          command: npm install
      - run:
          name: Running Webpack
          command: npm run build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: dist
          to: 's3://techgem1986/dist'
      - aws-s3/copy:
          from: index.html
          to: 's3://techgem1986'
workflows:
  build-upload-s3:
    jobs:
      - build-and-upload
#          context:
#            - SonarCloud
#            - DockerHub
#      - aws-ecs/deploy-service-update:
#          cluster-name: 'techgem1986'
#          container-image-name-updates: 'container=blogger-service,image-and-tag=docker.io/techgem1986/blogger-service:latest'
#          family: 'blogger-service'
#          requires:
#            - build-and-publish
#          context:
#            - AWS